"""add gpu_info to workers

Revision ID: 35757a668715
Revises: 4f50ea205f4b
Create Date: 2026-05-03 16:02:26.828339

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35757a668715"
down_revision: Union[str, None] = "4f50ea205f4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("gpu_info", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "gpu_info")
    # ### end Alembic commands ###
