"""add priority and nullable worker_id

Revision ID: 79cd4eec260e
Revises: 35757a668715
Create Date: 2026-05-03 16:24:36.884612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79cd4eec260e"
down_revision: Union[str, None] = "35757a668715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("priority", sa.Integer(), nullable=False, server_default="0")
    )
    op.alter_column(
        "jobs", "worker_id", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs", "worker_id", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    op.drop_column("jobs", "priority")
    # ### end Alembic commands ###
